Adiciona exercícios JavaScript Nível 1
aceleradora-TW/trilha-de-estudos pull request #10
Opened 2018-03-29 03:53 UTC by mvoliveira

2018-03-29 18:37 UTC, yrachid requested changes

2018-03-29 18:37 UTC, othman853 commented on README.md
> +- [Exercícios - Nível 1](https://docs.google.com/document/d/1Rlxx1CG20qpHxqgtksgCHNbnYgqY7gfUZsPoxmIYIr8/edit)
E se esses exercícios fossem uma página markdown em vez de um google docs? Poderíamos adicionar a página nesse repositório, inclusive. 

As vantagens que eu vejo nisso são:
- Syntax highlighting 
- Mais fácil de escrever linhas de código em markdown do que google docs (identação, por exemplo)
- Fica no mesmo lugar que a trilha de estudos
- Poderíamos inclusive adicionar exemplos de código

2018-03-29 18:37 UTC, yrachid approved these changes

2018-03-29 18:38 UTC, othman853 commented
Dei `request changes` antes para garantir que meu comentário seria lido, foi mal hehehe.

2018-03-29 18:39 UTC, othman853 commented on README.md
> +- [Exercícios - Nível 1](https://docs.google.com/document/d/1Rlxx1CG20qpHxqgtksgCHNbnYgqY7gfUZsPoxmIYIr8/edit)
Faria sentido testarmos o [Github classroom](https://classroom.github.com/) para esses exercícios?

2018-03-29 23:09 UTC, ClaudiaStrm commented
Nãããããoooo, aquele doc não!!!!!
Botei num gist, olha que bonito. https://gist.github.com/ClaudiaStrm/f4daccf723f9155d2a376ffb8845111c

2018-03-30 01:46 UTC, mvoliveira commented on README.md
> +- [Exercícios - Nível 1](https://docs.google.com/document/d/1Rlxx1CG20qpHxqgtksgCHNbnYgqY7gfUZsPoxmIYIr8/edit)
A @ClaudiaStrm vai dar uma olhada no Github classroom. 
Acho que com o esse doc do google drive realmente não ficou legal, mas poderíamos fazer um "MVP" desse nível da trilha, inserindo o Gist enquanto alguém configura ou adiciona esse material no Github classroom(não sei como funciona).

2018-04-04 02:05 UTC, mvoliveira commented
Não façam merge aqui antes da sessão que utilizará esses exercícios :+1:

2018-04-05 12:48 UTC, closed without merging